from django.core.management.base import BaseCommand
from dashboard.models import PollutantType


class Command(BaseCommand):
    help = 'Populate the database with comprehensive pollutant types based on international standards'

    def handle(self, *args, **options):
        pollutants_data = [
            # CRITERIA AIR POLLUTANTS
            {
                'name': 'Particulate Matter (PM2.5)',
                'chemical_formula': '',
                'cas_number': '',
                'category': 'particulate',
                'subcategory': 'Fine Particulate Matter',
                'unit': 'µg/m³',
                'who_standard': 15.0,
                'who_averaging_time': '24-hour',
                'nesrea_standard': 35.0,
                'nesrea_averaging_time': '24-hour',
                'epa_standard': 35.0,
                'epa_averaging_time': '24-hour',
                'eu_standard': 25.0,
                'description': 'Fine particulate matter with diameter ≤2.5 micrometers',
                'health_effects': 'Respiratory and cardiovascular diseases, premature death, lung cancer',
                'environmental_effects': 'Visibility reduction, ecosystem damage',
                'sources': 'Vehicle emissions, industrial processes, biomass burning, secondary formation',
                'sampling_method': 'Gravimetric sampling, beta attenuation, light scattering',
                'analytical_method': 'EPA Method IO-2.1, EN 12341',
                'detection_limit': 1.0,
            },
            {
                'name': 'Particulate Matter (PM10)',
                'chemical_formula': '',
                'cas_number': '',
                'category': 'particulate',
                'subcategory': 'Coarse Particulate Matter',
                'unit': 'µg/m³',
                'who_standard': 45.0,
                'who_averaging_time': '24-hour',
                'nesrea_standard': 150.0,
                'nesrea_averaging_time': '24-hour',
                'epa_standard': 150.0,
                'epa_averaging_time': '24-hour',
                'eu_standard': 50.0,
                'description': 'Particulate matter with diameter ≤10 micrometers',
                'health_effects': 'Respiratory irritation, aggravation of asthma and heart disease',
                'environmental_effects': 'Visibility reduction, soiling',
                'sources': 'Dust, pollen, mold, vehicle emissions, industrial processes',
                'sampling_method': 'Gravimetric sampling, beta attenuation',
                'analytical_method': 'EPA Method IO-2.1, EN 12341',
                'detection_limit': 2.0,
            },
            {
                'name': 'Nitrogen Dioxide',
                'chemical_formula': 'NO2',
                'cas_number': '10102-44-0',
                'category': 'criteria_air',
                'subcategory': 'Nitrogen Oxides',
                'unit': 'µg/m³',
                'molecular_weight': 46.01,
                'who_standard': 40.0,
                'who_averaging_time': 'Annual',
                'nesrea_standard': 100.0,
                'nesrea_averaging_time': '1-hour',
                'epa_standard': 100.0,
                'epa_averaging_time': '1-hour',
                'eu_standard': 40.0,
                'description': 'Reddish-brown gas, major air pollutant',
                'health_effects': 'Respiratory irritation, reduced lung function, increased infections',
                'environmental_effects': 'Acid rain formation, eutrophication, ozone formation',
                'sources': 'Vehicle emissions, power plants, industrial combustion',
                'sampling_method': 'Chemiluminescence, passive sampling',
                'analytical_method': 'EPA Method TO-17, EN 14211',
                'detection_limit': 1.0,
            },
            {
                'name': 'Sulfur Dioxide',
                'chemical_formula': 'SO2',
                'cas_number': '7446-09-5',
                'category': 'criteria_air',
                'subcategory': 'Sulfur Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 64.07,
                'who_standard': 20.0,
                'who_averaging_time': '24-hour',
                'nesrea_standard': 365.0,
                'nesrea_averaging_time': '24-hour',
                'epa_standard': 196.0,
                'epa_averaging_time': '24-hour',
                'eu_standard': 125.0,
                'description': 'Colorless gas with pungent odor',
                'health_effects': 'Respiratory irritation, bronchoconstriction, cardiovascular effects',
                'environmental_effects': 'Acid rain, vegetation damage, building corrosion',
                'sources': 'Coal burning, oil refining, metal smelting, volcanic emissions',
                'sampling_method': 'UV fluorescence, wet chemistry',
                'analytical_method': 'EPA Method TO-26, EN 14212',
                'detection_limit': 2.0,
            },
            {
                'name': 'Carbon Monoxide',
                'chemical_formula': 'CO',
                'cas_number': '630-08-0',
                'category': 'criteria_air',
                'subcategory': 'Carbon Compounds',
                'unit': 'mg/m³',
                'molecular_weight': 28.01,
                'who_standard': 10.0,
                'who_averaging_time': '8-hour',
                'nesrea_standard': 10.0,
                'nesrea_averaging_time': '8-hour',
                'epa_standard': 10.0,
                'epa_averaging_time': '8-hour',
                'eu_standard': 10.0,
                'description': 'Colorless, odorless toxic gas',
                'health_effects': 'Reduced oxygen delivery, cardiovascular stress, neurological effects',
                'environmental_effects': 'Ozone formation precursor',
                'sources': 'Vehicle emissions, incomplete combustion, industrial processes',
                'sampling_method': 'Non-dispersive infrared spectroscopy',
                'analytical_method': 'EPA Method TO-13A, EN 14626',
                'detection_limit': 0.1,
            },
            {
                'name': 'Ozone',
                'chemical_formula': 'O3',
                'cas_number': '10028-15-6',
                'category': 'criteria_air',
                'subcategory': 'Photochemical Oxidants',
                'unit': 'µg/m³',
                'molecular_weight': 48.00,
                'who_standard': 100.0,
                'who_averaging_time': '8-hour',
                'nesrea_standard': 157.0,
                'nesrea_averaging_time': '8-hour',
                'epa_standard': 157.0,
                'epa_averaging_time': '8-hour',
                'eu_standard': 120.0,
                'description': 'Secondary pollutant formed by photochemical reactions',
                'health_effects': 'Respiratory irritation, reduced lung function, asthma aggravation',
                'environmental_effects': 'Vegetation damage, crop yield reduction',
                'sources': 'Secondary formation from NOx and VOCs in sunlight',
                'sampling_method': 'UV photometry, chemiluminescence',
                'analytical_method': 'EPA Method TO-3, EN 14625',
                'detection_limit': 1.0,
            },
            
            # HEAVY METALS
            {
                'name': 'Lead',
                'chemical_formula': 'Pb',
                'cas_number': '7439-92-1',
                'category': 'heavy_metal',
                'subcategory': 'Toxic Metals',
                'unit': 'µg/m³',
                'molecular_weight': 207.2,
                'who_standard': 0.5,
                'who_averaging_time': 'Annual',
                'nesrea_standard': 1.5,
                'nesrea_averaging_time': 'Quarterly',
                'epa_standard': 0.15,
                'epa_averaging_time': 'Quarterly',
                'eu_standard': 0.5,
                'description': 'Toxic heavy metal, bioaccumulative',
                'health_effects': 'Neurological damage, developmental delays, cardiovascular effects',
                'environmental_effects': 'Ecosystem contamination, bioaccumulation',
                'sources': 'Legacy gasoline, paint, industrial processes, mining',
                'sampling_method': 'High-volume sampling on filters',
                'analytical_method': 'ICP-MS, AAS, EPA Method IO-3.1',
                'detection_limit': 0.01,
            },
            {
                'name': 'Mercury',
                'chemical_formula': 'Hg',
                'cas_number': '7439-97-6',
                'category': 'heavy_metal',
                'subcategory': 'Toxic Metals',
                'unit': 'µg/m³',
                'molecular_weight': 200.59,
                'who_standard': 1.0,
                'who_averaging_time': 'Annual',
                'epa_standard': 0.3,
                'epa_averaging_time': 'Annual',
                'description': 'Highly toxic heavy metal, bioaccumulative',
                'health_effects': 'Neurological damage, kidney damage, developmental effects',
                'environmental_effects': 'Bioaccumulation in food chain, ecosystem toxicity',
                'sources': 'Coal combustion, industrial processes, waste incineration',
                'sampling_method': 'Gold amalgamation, impinger sampling',
                'analytical_method': 'Cold vapor AAS, ICP-MS, EPA Method 1631',
                'detection_limit': 0.001,
            },
            {
                'name': 'Cadmium',
                'chemical_formula': 'Cd',
                'cas_number': '7440-43-9',
                'category': 'heavy_metal',
                'subcategory': 'Toxic Metals',
                'unit': 'µg/m³',
                'molecular_weight': 112.41,
                'who_standard': 5.0,
                'who_averaging_time': 'Annual',
                'eu_standard': 5.0,
                'description': 'Toxic heavy metal, carcinogenic',
                'health_effects': 'Kidney damage, bone disease, cancer',
                'environmental_effects': 'Soil contamination, plant toxicity',
                'sources': 'Industrial processes, waste incineration, fertilizers',
                'sampling_method': 'High-volume sampling on filters',
                'analytical_method': 'ICP-MS, AAS, EPA Method IO-3.1',
                'detection_limit': 0.005,
            },
            {
                'name': 'Arsenic',
                'chemical_formula': 'As',
                'cas_number': '7440-38-2',
                'category': 'heavy_metal',
                'subcategory': 'Metalloids',
                'unit': 'µg/m³',
                'molecular_weight': 74.92,
                'who_standard': 6.6,
                'who_averaging_time': 'Annual',
                'eu_standard': 6.0,
                'description': 'Toxic metalloid, carcinogenic',
                'health_effects': 'Cancer, cardiovascular disease, neurological effects',
                'environmental_effects': 'Soil and water contamination',
                'sources': 'Industrial processes, mining, pesticides, natural sources',
                'sampling_method': 'High-volume sampling on filters',
                'analytical_method': 'ICP-MS, AAS, EPA Method IO-3.1',
                'detection_limit': 0.002,
            },
            {
                'name': 'Chromium',
                'chemical_formula': 'Cr',
                'cas_number': '7440-47-3',
                'category': 'heavy_metal',
                'subcategory': 'Transition Metals',
                'unit': 'µg/m³',
                'molecular_weight': 51.996,
                'description': 'Heavy metal, hexavalent form is carcinogenic',
                'health_effects': 'Respiratory irritation, cancer (Cr VI), skin sensitization',
                'environmental_effects': 'Soil and water contamination',
                'sources': 'Industrial processes, leather tanning, metal plating',
                'sampling_method': 'High-volume sampling on filters',
                'analytical_method': 'ICP-MS, AAS, EPA Method IO-3.1',
                'detection_limit': 0.01,
            },
            
            # VOLATILE ORGANIC COMPOUNDS
            {
                'name': 'Benzene',
                'chemical_formula': 'C6H6',
                'cas_number': '71-43-2',
                'category': 'voc',
                'subcategory': 'BTEX Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 78.11,
                'who_standard': 1.7,
                'who_averaging_time': 'Annual',
                'eu_standard': 5.0,
                'description': 'Aromatic hydrocarbon, known carcinogen',
                'health_effects': 'Leukemia, bone marrow depression, neurological effects',
                'environmental_effects': 'Groundwater contamination, ozone formation',
                'sources': 'Vehicle emissions, industrial processes, gasoline evaporation',
                'sampling_method': 'Sorbent tube sampling, canister sampling',
                'analytical_method': 'GC-MS, EPA Method TO-17, TO-15',
                'detection_limit': 0.1,
            },
            {
                'name': 'Toluene',
                'chemical_formula': 'C7H8',
                'cas_number': '108-88-3',
                'category': 'voc',
                'subcategory': 'BTEX Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 92.14,
                'who_standard': 260.0,
                'who_averaging_time': '24-hour',
                'description': 'Aromatic hydrocarbon solvent',
                'health_effects': 'Neurological effects, respiratory irritation',
                'environmental_effects': 'Ozone formation, groundwater contamination',
                'sources': 'Vehicle emissions, industrial solvents, paint thinners',
                'sampling_method': 'Sorbent tube sampling, canister sampling',
                'analytical_method': 'GC-MS, EPA Method TO-17, TO-15',
                'detection_limit': 0.2,
            },
            {
                'name': 'Xylene (total)',
                'chemical_formula': 'C8H10',
                'cas_number': '1330-20-7',
                'category': 'voc',
                'subcategory': 'BTEX Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 106.17,
                'who_standard': 870.0,
                'who_averaging_time': '24-hour',
                'description': 'Aromatic hydrocarbon mixture (ortho, meta, para isomers)',
                'health_effects': 'Neurological effects, respiratory irritation',
                'environmental_effects': 'Ozone formation, groundwater contamination',
                'sources': 'Vehicle emissions, industrial solvents, gasoline',
                'sampling_method': 'Sorbent tube sampling, canister sampling',
                'analytical_method': 'GC-MS, EPA Method TO-17, TO-15',
                'detection_limit': 0.3,
            },
            {
                'name': 'Ethylbenzene',
                'chemical_formula': 'C8H10',
                'cas_number': '100-41-4',
                'category': 'voc',
                'subcategory': 'BTEX Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 106.17,
                'who_standard': 22000.0,
                'who_averaging_time': '24-hour',
                'description': 'Aromatic hydrocarbon',
                'health_effects': 'Respiratory and eye irritation, possible carcinogen',
                'environmental_effects': 'Ozone formation, groundwater contamination',
                'sources': 'Vehicle emissions, industrial processes, gasoline',
                'sampling_method': 'Sorbent tube sampling, canister sampling',
                'analytical_method': 'GC-MS, EPA Method TO-17, TO-15',
                'detection_limit': 0.2,
            },
            {
                'name': 'Formaldehyde',
                'chemical_formula': 'CH2O',
                'cas_number': '50-00-0',
                'category': 'voc',
                'subcategory': 'Aldehydes',
                'unit': 'µg/m³',
                'molecular_weight': 30.03,
                'who_standard': 100.0,
                'who_averaging_time': '30-minute',
                'description': 'Aldehyde, known carcinogen',
                'health_effects': 'Respiratory irritation, cancer, sensitization',
                'environmental_effects': 'Ozone formation',
                'sources': 'Building materials, vehicle emissions, industrial processes',
                'sampling_method': 'DNPH cartridge sampling, impinger sampling',
                'analytical_method': 'HPLC, EPA Method TO-11A',
                'detection_limit': 0.5,
            },
            
            # POLYCYCLIC AROMATIC HYDROCARBONS
            {
                'name': 'Benzo(a)pyrene',
                'chemical_formula': 'C20H12',
                'cas_number': '50-32-8',
                'category': 'pac',
                'subcategory': 'PAH',
                'unit': 'ng/m³',
                'molecular_weight': 252.31,
                'who_standard': 0.12,
                'who_averaging_time': 'Annual',
                'eu_standard': 1.0,
                'description': 'Polycyclic aromatic hydrocarbon, potent carcinogen',
                'health_effects': 'Cancer, mutagenic effects',
                'environmental_effects': 'Persistent organic pollutant, bioaccumulation',
                'sources': 'Combustion processes, vehicle emissions, industrial activities',
                'sampling_method': 'High-volume sampling on filters and PUF',
                'analytical_method': 'GC-MS, HPLC, EPA Method TO-13A',
                'detection_limit': 0.01,
            },
            
            # PHYSICAL PARAMETERS
            {
                'name': 'Total Suspended Particles',
                'chemical_formula': '',
                'cas_number': '',
                'category': 'particulate',
                'subcategory': 'Total Particulates',
                'unit': 'µg/m³',
                'nesrea_standard': 250.0,
                'nesrea_averaging_time': '24-hour',
                'description': 'Total suspended particulate matter',
                'health_effects': 'Respiratory irritation, reduced visibility',
                'environmental_effects': 'Visibility reduction, soiling',
                'sources': 'Dust, industrial processes, construction activities',
                'sampling_method': 'High-volume sampling',
                'analytical_method': 'Gravimetric analysis',
                'detection_limit': 5.0,
            },
            {
                'name': 'Hydrogen Sulfide',
                'chemical_formula': 'H2S',
                'cas_number': '7783-06-4',
                'category': 'criteria_air',
                'subcategory': 'Sulfur Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 34.08,
                'who_standard': 150.0,
                'who_averaging_time': '24-hour',
                'description': 'Toxic gas with rotten egg odor',
                'health_effects': 'Eye irritation, respiratory effects, neurological effects at high levels',
                'environmental_effects': 'Corrosion, odor nuisance',
                'sources': 'Industrial processes, sewage treatment, natural gas',
                'sampling_method': 'Impinger sampling, passive sampling',
                'analytical_method': 'Ion chromatography, colorimetric methods',
                'detection_limit': 1.0,
            },
            {
                'name': 'Ammonia',
                'chemical_formula': 'NH3',
                'cas_number': '7664-41-7',
                'category': 'criteria_air',
                'subcategory': 'Nitrogen Compounds',
                'unit': 'µg/m³',
                'molecular_weight': 17.03,
                'who_standard': 200.0,
                'who_averaging_time': '24-hour',
                'description': 'Alkaline gas, precursor to particulate matter',
                'health_effects': 'Respiratory and eye irritation, chemical burns',
                'environmental_effects': 'Eutrophication, secondary PM formation',
                'sources': 'Agriculture, industrial processes, vehicle emissions',
                'sampling_method': 'Impinger sampling, denuder sampling',
                'analytical_method': 'Ion chromatography, colorimetric methods',
                'detection_limit': 2.0,
            },
            
            # ADDITIONAL IMPORTANT POLLUTANTS
            {
                'name': 'Nitric Oxide',
                'chemical_formula': 'NO',
                'cas_number': '10102-43-9',
                'category': 'criteria_air',
                'subcategory': 'Nitrogen Oxides',
                'unit': 'µg/m³',
                'molecular_weight': 30.01,
                'description': 'Precursor to NO2 and ozone formation',
                'health_effects': 'Respiratory irritation, ozone formation',
                'environmental_effects': 'Acid rain formation, eutrophication',
                'sources': 'Vehicle emissions, power plants, industrial combustion',
                'sampling_method': 'Chemiluminescence',
                'analytical_method': 'EPA Method TO-17, EN 14211',
                'detection_limit': 1.0,
            },
            {
                'name': 'Total Volatile Organic Compounds',
                'chemical_formula': '',
                'cas_number': '',
                'category': 'voc',
                'subcategory': 'Total VOCs',
                'unit': 'µg/m³',
                'description': 'Sum of all volatile organic compounds',
                'health_effects': 'Variable depending on specific compounds',
                'environmental_effects': 'Ozone formation, smog',
                'sources': 'Industrial processes, vehicle emissions, solvents',
                'sampling_method': 'FID measurement, canister sampling',
                'analytical_method': 'GC-FID, EPA Method TO-12',
                'detection_limit': 10.0,
            },
        ]

        created_count = 0
        updated_count = 0

        for pollutant_data in pollutants_data:
            pollutant, created = PollutantType.objects.get_or_create(
                name=pollutant_data['name'],
                defaults=pollutant_data
            )
            
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'Created pollutant: {pollutant.name}')
                )
            else:
                # Update existing pollutant with new data
                for key, value in pollutant_data.items():
                    if key != 'name':  # Don't update the name field
                        setattr(pollutant, key, value)
                pollutant.save()
                updated_count += 1
                self.stdout.write(
                    self.style.WARNING(f'Updated pollutant: {pollutant.name}')
                )

        self.stdout.write(
            self.style.SUCCESS(
                f'\nSummary:\n'
                f'- Created: {created_count} new pollutants\n'
                f'- Updated: {updated_count} existing pollutants\n'
                f'- Total pollutants in database: {PollutantType.objects.count()}'
            )
        )